### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by deini** [ikatyang/generator-ts-jest#82]
👋 I have a couple of questions of the usage of this generator.

- Why doesn't it generate a package.json with the dependencies (jest/eslint/etc)?
- Can it generate a simple dummy class in `index.ts` and have a dummy test using that class for reference?

**Comment by ikatyang** [comment]
> Why doesn't it generate a package.json with the dependencies (jest/eslint/etc)?

It installs dependencies dynamically:

https://github.com/ikatyang/generator-ts-jest/blob/f68d180c90b38a951ba9e95595fdca229a638438/src/index.ts#L66-L70

But it seems not working now, I'll fix it later.

> Can it generate a simple dummy class in index.ts and have a dummy test using that class for reference?

Sure, but I think a dummy function with test should be enough?

**Comment by deini** [comment]
> But it seems not working now, I'll fix it later.

Awesome! I thought it was just not part of the generator

>Sure, but I think a dummy function with test should be enough?

Yes, a dummy function with test should be enough.

---

Follow up, since I'm not too familiar with yeoman:
If I generated a project with this generator, then you push a new version, whats the best way to upgrade?

Should I:
- Just check the changelog and manually doing those changes in my project?
- Generate a new project and move my files and git history?

**Comment by ikatyang** [comment]
I personally uses yeoman as an one-time generator (for quick start), i.e. I always uses the newest generator to create my new project, but the old projects still remain the same.

If you'd like to upgrade it, I'd recommend to do `1.` if it's just a small change, otherwise `2.`.

**Comment by ikatyang** [comment]
Closed #82 via #88 and #89.

Published [v1.3.0](https://github.com/ikatyang/generator-ts-jest/blob/master/CHANGELOG.md#130-2017-10-21).
