### ISSUE TITLE
Couldn't find github username

### ISSUE THREAD

**Issue by deini** [ikatyang/generator-ts-jest#94]
```
❯ yo ts-jest
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Couldn't find username for `redacted@work-mail.com`
    at ghGot.then.result 
```

Getting this when running the generator where my git email is not my primary GitHub email.

**Comment by krishnaPC** [comment]
Can you please reopen this? I am getting the same error on running the command `yo ts-jest`.

`Error ts-jest

Couldn't find username for `krishna.prasad@email.com``
